### ISSUE TITLE
JS not minimised

### ISSUE THREAD

**Issue by highacid** [optimalisatie/above-the-fold-optimization#1]
Is this only for known plugins in special Analitics and so on? I was hopping it will minify and pass the render-blockin fully. It did not passed JS optimisation, anything required for this?

**Comment by highacid** [comment]
And that is what? A way to reply say fuck off? Ir just ignorance... in its final state.

**Comment by optimalisatie** [comment]
Hi Highacid,

The issue is from more then 6 months ago. The plugin has been advanced greatly in the past months and the problem you seek a solution for has been completely solved by an innovation from 2 months ago. 

The new version of the plugin contains a Javascript Proxy that is even capable to (automatically) handle script injected scripts. By simply enabling it the Google PageSpeed issue will be solved.

The old javascript localization system has been removed.

Best Regards,
Jan Jaap
info@pagespeed.pro
