### ISSUE TITLE
Empty Critical CSS after DB migration

### ISSUE THREAD

**Issue by blauwhelm** [optimalisatie/above-the-fold-optimization#100]
Hi,

I'm using your plugin with good success! When I'm migrating my DB from my test server to the live server, the Critical CSS is empty. The theme folder is not changed, all files in the abovethefold folder are the same. The plugin recognizes all the pages I've made, but not the CSS in those files. When I rename the css folder in the abovethefold folder, refresh, delete the newly generated css folder and rename the old css folder back, it works again. What's also strange is that I don't get this problem when I'm migrating from live to test. It is a multisite environment also.

Hopefully you can help me with this problem!

Thanks,
Jan

**Comment by optimalisatie** [comment]
Hi Jan,

Thank you very much for your feedback!

It is a small issue. For performance (instead of reading the critical CSS directory on each page load), the plugin stores the critical CSS file paths in WordPress options and will therefor not see the critical CSS files when the site is moved to a new server. Of course this shouldn't happen in the admin panel and we will add it to the list with issues to resolve.

Due to the plugin being removed from WordPress.org, this plugin doesn't have a priority. For now it may be best to simply use the directory hack that you described. It costs a few seconds and will resolve the issue.

**Comment by optimalisatie** [comment]
The following option is used. It may be best to simply use the directory hack, it is simple and it will be reliable (the plugin will then re-create the critical css files list).

```$fileconfig = get_option('abovethefold-criticalcss', array());
if (!is_array($fileconfig)) {
   $fileconfig = array();
}```
