### ISSUE TITLE
Above The Fold Optimization 403 Forbidden for some files.

### ISSUE THREAD

**Issue by utags** [optimalisatie/above-the-fold-optimization#12]
Hi there,

When I see my web page errors, I can see above the fold optimization delivery URLS got "403 Forbidden" error. For an example, following type URL's. https:///cdn2-drcrhub.r.worldssl.net/ is my CDN domain.

> https://www.drcrhub.com/?url=https%3A//cdn2-drcrhub.r.worldssl.net/wp-content/themes/focus-pro/js/responsive-menu.js&type=js&abtf-proxy=542993957b5d1877d1e34e348a749a0e

If I visit that like via web browser, it shows "**The resource is not specifically included via the include list.**"

**Comment by optimalisatie** [comment]
Hi Utags,

You have discovered a bug in the situation where you use the HTML5 Script Loader with localStorage, Fetch API and Web Worker and specifically define what scripts should be proxied.

For the HTML5 script loader to work, it requires the resource proxy to bypass [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). The HTML5 script loader sends any scripts that are on a different host (in your case `cdn2.domain.com`) to the proxy. 

The plugin does offer a solution to resolve the issue while maintaining the desired configuration. It is possible to define a CDN hostname in the proxy. The proxy will then know that files served on cdn2.domain.com are local files and processes them accordingly.

The proxy can also be configured with a CDN on JSON config object level so that it is possible to serve specific resources on a different CDN. The parameter is `cdn`.

Let me know if configuring the CDN in the proxy settings resolves the issue. 

In our new plugin, the proxy will be improved greatly so that it will handle these issues automatically.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by utags** [comment]
Thank you Jan your reply. After I added a same CDN domain name to "Proxy CDN" and "Proxy URL" now I can see the 404 Not Found errors.
