### ISSUE TITLE
Any way to Prioritize visible content?

### ISSUE THREAD

**Issue by utags** [optimalisatie/above-the-fold-optimization#13]
I think it would be nice if this plugin offer an option to "**Prioritize visible conten**t". Because Google page speed insight also measure the prioritize visible content.

**Comment by optimalisatie** [comment]
Hi Utags,

Thank you for your suggestion!

Regrettably, the Google PageSpeed rule is complex. For example, when you use a javascript library to render a mobile menu button and combine all javascript into 1 file with a size of 1MB, the browser will first need to download the javascript file before the above the fold content can be rendered. This will trigger the Google PageSpeed rule `Prioritize visible content` or `Reduce the size of the above-the-fold content`.

https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent

To solve the issue it would be required to include the mobile menu javascript inline or in a separate file or alternatively, to rewrite the mobile menu button in pure CSS so that no javascript is required to render the above the fold content.

The possible issues causing the `Prioritize visible content` penalty are complex. Sometimes it is a combination of factors and it is required to determine the shortest and least conflict-prone path to a solution.

We are currently developing a new plugin that will make solving the `Prioritize visible content` issue more easy. The plugin will be ready in a few months.

I hope that this information is helpful! 

Best Regards,
Jan Jaap
info@pagespeed.pro
