### ISSUE TITLE
 Proxy Scripts + SSL = Avoid landing page redirects

### ISSUE THREAD

**Issue by azirer** [optimalisatie/above-the-fold-optimization#20]
I enabled the Proxy scripts and entered only one script at the include list: https://www.google-analytics.com/analytics.js

so i see a new request like this https://mydomain.com.cy/?url=https%3A//www.google-analytics.com/analytics.js&type=js&abtf-proxy=57273ec05d6d349g36789fc8a45c4b22

I tried to see the http code in the network tab of Chrome for this request where I see no code at all just the word cancelled in red.

I went to pagespeed insights and I noticed that the Avoid landing page redirects is triggered
"Your page has 2 redirects. Redirects introduce additional delays before the page can be loaded.
Avoid landing page redirects for the following chain of redirected URLs.
https://mydomain.com.cy/?url=https%3A//www.google-analytics.com/analytics.js&type=js&abtf-proxy=57273ec05d6d349g36789fc8a45c4b22
http://mydomain.com.cy/
https://mydomain.com.cy/"

Note that on my nginx configuration I redirect traffic from http to https

Any ideas?

**Comment by optimalisatie** [comment]
Hi Azirer,

Thank you for reporting the problem!

The problem may be caused by a plugin or server security setting that redirects URL's with a query string to http://mydomain.com.cy/ that is redirected again to https:// by nginx. Because the URL is first redirected to http (which indicates a fixed redirect without protocol relativity) I suspect that the cause is a WordPress security plugin.

Do you use any WordPress security plugins or plugins that could force the redirect? The redirect may also be forced by nginx.

To find the origin of the redirect it is an option to check the server headers and HTML content on http://web-sniffer.net/ It may reveal information about the redirect.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by azirer** [comment]
I've just tested queries on my sites like 
`http://mydomain.com/_auto.js?_req=L3Rlc3QbgYFnZS8%3D` and they all redirected (One redirect) to `https://...`

This `https://mydomain.com/_auto.js?_req=L3Rlc3QbgYFnZS8%3D` or any other `https://mydomain.com/?foo=bar` is not redirected and returns 
```
Request Method:GET
Status Code:200 OK
```

So I went back and tried `https://mydomain.com/?url=https%3A//www.google-analytics.com/analytics.js&type=js&abtf-proxy=57273ec05d6d349g36789fc8a45c4b22` This returns 302 Status code

while this 
`https://mydomain.com/?url=//www.google-analytics.com/analytics.js&type=js&abtf-proxy=57273ec05d6d349g36789fc8a45c4b22` returns valid code 200 and I see the output

I noticed this also on a fresh wordpress install with twentyfourteen ond only abtf active. So it's not a plugin. It's either my nginx setup, or a modsecurity rule or a another server setting. Can you try the last two requests on your website and see what you get? Or is there any demo anywhere to inspect it on chrome's network tab? 
Thank you

**Comment by optimalisatie** [comment]
Hi azirer,

On other installations the URL will always simply proxy the resource or show an error message to inform what went wrong (e.g. when the resource is not allowed by the proxy).

Status 302 = temporary redirect. The proxy (and ABTF plugin) does not use 302 redirects so the origin must be from a security solution or server configuration.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by azirer** [comment]
It's not nginx proxy it is modsecurity. Specifically it triggers the rule ID 950120 of the OWASP rules.
950120: Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link,  CRITICAL, Action: 302	

Here is the rule
`SecRule ARGS "^(?:ht|f)tps?://(.*)$" "chain, phase:request, rev:'3', ver:'OWASP_CRS/3.0.0', maturity:'9', accuracy:'9', t:none, capture, ctl:auditLogParts=+E, block, msg:'Possible Remote File Inclusion (RFI) Attack: Off-Domain Reference/Link', logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}', id:'950120', severity:'CRITICAL', tag:'application-multi', tag:'language-multi', tag:'platform-multi', tag:'attack-remote file inclusion', tag:'OWASP_CRS/WEB_ATTACK/RFI'"
 SecRule TX:1 "!@beginsWith %{request_headers.host}" "setvar:'tx.msg=%{rule.msg}', setvar:tx.rfi_score=+%{tx.critical_anomaly_score}, setvar:tx.anomaly_score=+%{tx.critical_anomaly_score}, setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/RFI-%{matched_var_name}=%{tx.1}"`

Removing the protocol (https in my case or http in other cases) from `?url=//www.google-analytics.com/analytics.js....` fixes the issue. and I think that I shouldn't disable this specific rule in modsec.

Anyway why does ABTF try to proxy `https://www.google-analytics.com/analytics.js` while I have explicitly declared  in the "Proxy Include List" to proxy the `//www.google-analytics.com/analytics.js`

Can you leave it up to the user to define this?

**Comment by optimalisatie** [comment]
Hi azirer,

The plugin translates relative protocol URLs to get a steady base URL to use as cache key. For example, if you link both //www.google-analytics.com and https://www.google-analytics.com from the same page, the proxy will load 1 script from its cache. localStorage has limited capacity so this is an important feature.

As for the Mod Security rule, it simply checks if http(s) is present in the request. It therefor triggers when the query string contains https://. To use the proxy, it would be required to disable the rule. It would also be possible to modify the proxy to base64 encode/decode URL's but that would be a more advanced customization.

Our engineers will investigate the issue for the next update so that the problem may be solved.

Best Regards,
Jan Jaap
info@pagespeed.pro
