### ISSUE TITLE
Problem with WooCommerce and some other questions

### ISSUE THREAD

**Issue by Seek51** [optimalisatie/above-the-fold-optimization#21]
Hello,

If i enable the “Optimize CSS Delivery” i have problem with my code in functions.php in the
theme folder.
I add some line to the functions.php, to give WooCommerce the information, how many products should be shown on one page.
// Number of products to show per page
add_filter( ‘loop_shop_per_page’, function ( $cols ) {return 24;}, 20 );
// Number or products per row
add_filter(‘loop_shop_columns’, ‘loop_columns’);
if (!function_exists(‘loop_columns’))
{function loop_columns() {return 4; }} // 4 products per row

After activating the “Optimize CSS Delivery”, my WooCommerce show me the wrong column and lines 🙁

A other question:
I have installed Fastest Cache AND Autoptimize.
These two programs are supported from your plugin.
How should i make the best settings in the Cache plugins?
Should i activate all options?
Or does your plugin these operation for me?

The last question:
If i go on my woocommerce into the checkout, i have mixed contens on my https connection.
The code is:
<!DOCTYPE html><html lang="de-DE" prefix="og: http://ogp.me/ns#" class="no-js"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"><link rel="profile" href="http://gmpg.org/xfn/11" /><link rel="pingback" href="https://www.ramser-elektro.at/xmlrpc.php" /> <!--[if lt IE 9]> <script src="https://www.ramser-elektro.at/wp-content/themes/ambition-pro/js/html5.min.js"></script>
.......................

Best regards

**Comment by optimalisatie** [comment]
Hi Seek51,

Thank you for reporting the problem!

Regarding the WooCommerce functions.php configuration issue. It is unlikely that the Optimize CSS Delivery setting is the cause of the problem since the functions.php filters affect PHP (the physical amount of products and columns to display) and the CSS delivery optimization simply loads CSS files asynchronously.

Do you have more details available regarding the problem? Is the issue a CSS issue or a physical HTML issue?

Regarding the plugins Fastest Cache and Autoptimize. The plugin support is limited to processing of minified CSS and javascript and emptying of the full page cache. The configuration of both plugins should be done manually. The optimal settings are different for each website so we are unable to advise on the best settings.

Regarding the mixed content error, that is most likely not related to the Above The Fold Optimization plugin. It may be a tracking tool / plugin such as Google Analytics for e-commerce that is loaded over http instead of https. The browser console (F12) shows the URL that is causing the mixed content error.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by Seek51** [comment]
OK. I solved some issues.

But i already having the problem with the woocommerce.
After i activate the option "Optimize CSS Delivery" , woocommerce shows me the 
incorrect picture format :-(
You can see it here: [https://www.pic-upload.de/gal-1048762/j4pmv/1.html](url)

I wrote back support an email, but didn't get any feedback.

Someone, who can help me?
Maybe just an error in the style sheet?

**Comment by Seek51** [comment]
No feedback anymore?
Problem with woocommerce still exist!!!
First, the site is loading normal, then the problem with the 
wrong symbols comes up.
I worte your support, but didn't get any feedback.

**Comment by optimalisatie** [comment]
The issues that you describe appears to be related to the (quality of) critical CSS. For example, the wrong symbols issue is caused by invalid critical CSS:

![abtf-quality-view-chinese-characters](https://cloud.githubusercontent.com/assets/8843669/23516170/bb7c52f8-ff6c-11e6-8c36-8d119ab98949.png)

What tool did you use to create the critical CSS? 

Have you tested the critical CSS with the quality test (PageSpeed menu -> Critical CSS Quality Test) and does the critical CSS match the full CSS view?

**Comment by Seek51** [comment]
Hello,

When i run the critical CSS Test with the online store,
the displayed page is OK. (See screenshot)
So i don't know what can be the problem.
![critical css test](https://cloud.githubusercontent.com/assets/25787892/23540669/02bcf610-ffe3-11e6-9d85-c383b5df80cf.JPG)

**Comment by Seek51** [comment]
I extracted the full CSS with "Critical CSS"/"Extract Full CSS" -> "Download"
		Then i put it here: https://jonassebastianohlsson.com/criticalpathcssgenerator/
		And use a minimizer. https://cssminifier.com/
		(Without minimizer, the same problem.)
		
		This is my Critical CSS Setting:
![critical](https://cloud.githubusercontent.com/assets/25787892/23548051/0a006394-0006-11e7-974b-382d52170f6a.JPG)
