### ISSUE TITLE
Proxy questions for a noob

### ISSUE THREAD

**Issue by mlava** [optimalisatie/above-the-fold-optimization#33]
Hi there. 
Great plugin, it's sped up my site already. 
I am having some issues with the js proxy. 
I wish to use Google tag manager with analytics and Facebook pixel. 
I set up exclusions:
googletagmanager.com/gtm.js

But pixels aren't firing. 
Is there a step by step for noobs anywhere? 
Do I need to add exclusions for any scripts called by the tags?

**Comment by thetwopct** [comment]
+ 1 - I would also like this, as I find it really confusing 😫

**Comment by optimalisatie** [comment]
Hi!

I've tested the proxy with the mentioned configuration and it appears to work without an issue.

https://test.pagespeed.pro/

The Google Tag Manager script (gtm.js) is proxied successfully (it doesn't need to be excluded).

```javascript
/** Javascript Proxy / Above The Fold Optimization v2.7.10
 * @url https://www.googletagmanager.com/gtm.js?id=GTM-PZM7Z6S
 * @expire 2017/04/25 10:35:05 */

/** Javascript Proxy / Above The Fold Optimization v2.7.10
 * @url https://www.google-analytics.com/analytics.js
 * @expire 2017/04/25 10:35:06 */

/** Javascript Proxy / Above The Fold Optimization v2.7.10
 * @url https://connect.facebook.net/en_US/fbevents.js
 * @expire 2017/04/25 10:35:06 */
```

Both the Facebook pixel and Google Analytics (Universal) are proxied and executed correctly.

![proxy-gtm-fbpixel-analytics](https://cloud.githubusercontent.com/assets/8843669/24330599/2648001a-1222-11e7-92de-4a383d90f181.png)

The following questions may lead to an answer/solution:

1) Have you checked the browser console (F12) to see if there are related javascript errors? 
2) Are the proxied files visible in the network tab?
3) Are you using the javascript async loading feature? If so, are you using localStorage cache (HTML5 script loader)?

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by mlava** [comment]
Hi Jan,
Thank you.
1. There are no js errors in console.
2. The files aren't seen in network tab.
3. Yes.

Given they're not seen in network tab, what is likely the issue.

My exact proxy exclusions are as follows:
```
googletagmanager.com/gtm.js
googletagmanager.com/ns.html
connect.facebook.net/en_US/fbevents.js
trackcmp.net
```

**Comment by mlava** [comment]
I took the gtm + fb entries out of the exclusions as you stated:
`The Google Tag Manager script (gtm.js) is proxied successfully (it doesn't need to be excluded).`

Still nothing in network tab :-(

**Comment by optimalisatie** [comment]
Hi mlava,

Have you enabled debug mode (for logged in admin users, on the settings tab) and is there any information in the console regarding the proxy / scripts?

**Comment by Nitin-Prabhakar** [comment]
@mlava  Thanks for the thread.
@optimalisatie I am grateful for this developer friendly plugin. Thanks much!

Do you use backbonejs for your scripting? because I am seeing these errors and am Actually, 
not sure what is triggering them, the plugin, or something else

Also, the WP Admin bar doesn't seem to rely too well on the plugin

![screenshot from 2017-04-12 02-45-13](https://cloud.githubusercontent.com/assets/15086525/24931439/e9dd1384-1f2a-11e7-8a40-5b8a73c8bc82.png)

**Comment by Nitin-Prabhakar** [comment]
Also, I just noted, 
## page speed insights 
asks me to specify a TTL for `proxied` scripts?
Is that normal?

![screenshot from 2017-04-12 06-33-16](https://cloud.githubusercontent.com/assets/15086525/24936835/4b8f5046-1f4a-11e7-8b32-d9c7b843d609.png)

**Comment by optimalisatie** [comment]
Hi Nitin,

Backbone.js is not part of the plugin. It must be a script on your website. The HTML5 script loader places scripts in a javascript blob for fast local loading so that the error appears to come from an unknown source. To find the exact source file it is possible to enable debug mode on the settings-tab to see references to the origin scripts in the browser console (F12).

Regarding the missing dependency `grofiles-cards`, is it certain that the script is actually being loaded? 

Regarding the cache header problem in PageSpeed Insights. The cached proxy source files are simply static resources on your server. The error indicates that the server configuration does not provide caching headers for static (javascript) files. To solve the issue it is required to edit .htaccess, nGinx configuration or ask your hosting provider to provide in caching header configuration.

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by Nitin-Prabhakar** [comment]
Hey Jan, 

Thanks for the details.

I am exploring the debug console now.

Regarding the grofiles ( I managed to read it is for the gravatar) error, Yes the script is being loaded by the browser, if thats what you meant.
[Here it is ](http://blog.nitinprabhakar.com/wp-content/plugins/jetpack/modules/wpgroho.js?ver=4.7.3)

I also have an ABTF console log , that posts, that the script in question , wpgroho.js , was loaded

But that is after the error, as shown

![screenshot from 2017-04-13 01-47-47](https://cloud.githubusercontent.com/assets/15086525/24977669/71a7ca32-1feb-11e7-9004-61da5505fc7a.png)

Is it possible, it is because of the jQuery dependency which is lazy loaded per my JS config?

**Comment by Nitin-Prabhakar** [comment]
Soo, I have now tried multiple permutations and combinations and the errors are definitely related to 
the `Optimize Javascript Loading` feature.
The errors of the sort above saying `dependency unmet`, seem to multiply over time for some reason.
As in,
Initially, the error is only 1 in number, but as the various scripts begin to async load, the errors compound for unmet dependencies being "Not loaded Yet"

Lazy loading JQUERY has no bearing on them as well, so I left it enabled
Proxying helps in caching and I have left it enabled.

I guess All the javascript libraries like backbone, Underscore, etc and 
internal Wordpress JS dependencies, 

ABSOLUTELY need a sync load and not async.

I know wordpress uses `register-script` methods, to `enqueue` scripts in the order it needs them,
but not sure if the `optimize javascript loading` feature, **Strictly** abides the order.

BTW, I did uncheck the *** Force Async*** box, 
Also added all dependencies to ***Exclude from Async*** list (one URL per line) as suggested, 
but the errors persisted.(Even after clearing all caches, cookies, and history)

**Comment by optimalisatie** [comment]
Hi Nitin,

Have you tried to exclude the `gprofiles-cards` related scripts? Maybe the script inclusion is incomplete or invalid causing the script loader to fail.

As for dependencies, the script loader is async only with (optional) dependency management.
