### ISSUE TITLE
Above the Fold installation messing up WordPress comments?

### ISSUE THREAD

**Issue by dalelowry** [optimalisatie/above-the-fold-optimization#34]
I installed Above the Fold yesterday on my site (dalecameronlowry.com) but was told today by readers they can no longer leave comments on my blog posts (for example at https://dalecameronlowry.com/email-marketing-provider-sendpulse-review/). They get this message:

ERROR: JavaScript and Cookies are required in order to post a comment. Please be sure JavaScript and Cookies are enabled in your browser. Then, please hit the back button on your browser, and try posting your comment again. (You may need to reload the page.)

I've recreated the issue by logging out of my admin and trying to leave a comment on my blog when using Chrome. If I disable Above the Fold, I can leave a comment. If it's on, even without a single setting ticked or enabled, I get the above error.

It seems to work Okay in Safari even with everything enabled and some critical CSS settings added.

I've disabled Above the Fold for now, but if anyone wants me to reenable it for troubleshooting, let me know.

**Comment by optimalisatie** [comment]
Hi dalelowry,

Thank you for reporting the problem!

Have you checked the browser console to see if there was a javascript error visible?

Some scripts do not natively support async loading. More information can be found in the following article about making Google AdSense scripts async compatible:

https://support.google.com/adsense/answer/3221666?hl=en

Since you noted that the problem does not occur in Safari, it appears to be javascript rendering related conflict. Sometimes a simple solution may be to encapsulate conflicting scripts in `jQuery(function($) { });` so that the script is started after the full HTML is loaded.

Let me know if you manage to resolve the issue!

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by dalelowry** [comment]
Sorry I didn't reply earlier. I'm not sure why I didn't see this at the time—maybe I was down a rabbit hole caused by a plugin conflict.

That's what this turned out to be. It  was related to WP Spamshield and a conflict it had with an unidentified plugin. I removed Spamshield and the problem went away.
