### ISSUE TITLE
+ sign issue

### ISSUE THREAD

**Issue by pratham2003** [optimalisatie/above-the-fold-optimization#40]
There is a small problem with the proxy part I think.
It seems like the proxy script requests for a 'space' %20 instead if the '+' sign %2B

This happens in the case of google custom search engine js/css.
URL that works : https://www.google.com/uds/api/search/1.0/some-unique-id-here/default+en.css
URL that doesn't : https://www.google.com/uds/api/search/1.0/some-unique-id-here/default%20en.css

Screenshot:
http://i.imgur.com/lRUpWrs.png

**Comment by optimalisatie** [comment]
Hi Pratham2003,

Thank you for taking the time to report the issue!

The proxy system will be redone in the next version. I've added the issue to the todo list, the issue will be solved in the next version!

Best Regards,
Jan Jaap
info@pagespeed.pro

**Comment by optimalisatie** [comment]
Hi @pratham2003,

After further testing we discovered that the proxy handles spaces in the correct way. Google's CSS file demands a `+` representation of a space while `%20` is the default representation. For example, the browser will convert spaces to %20 when you enter Google's unencoded URL in the address bar:

[https://www.google.com/uds/api/search/1.0/some-unique-id-here/default en.css](https://www.google.com/uds/api/search/1.0/some-unique-id-here/default en.css) (this link will not work because the browser converts the space to %20)

To resolve the issue you need to make sure that the Google URL is correctly URL encoded in the HTML.

Best Regards,
Jan Jaap
info@pagespeed.pro
