### ISSUE TITLE
Can't Proxy Google Analytics/Optimize/Tag Manager JS Files

### ISSUE THREAD

**Issue by jiiins** [optimalisatie/above-the-fold-optimization#45]
Is there a trick to proxy the various Google js files? When I exclude them from the proxy feature they work fine. If I leave them in, they don't get loaded correctly.

**Comment by optimalisatie** [comment]
Hi jiiins,

Thank you for reporting the issue!

Could you please let me know what Google scripts you try to proxy and what problems you experience?

**Comment by jiiins** [comment]
Hi opti,

the scripts are:
Tag Manager: https://www.googletagmanager.com/gtm.js
Optimize: https://optimize.google.com/optimize/inject/inject.js
Analytics: https://www.google-analytics.com/analytics.js

When they aren't excluded from proxy no events are fired (like GA's pageview).

**Comment by supernovae** [comment]
I think this is because the URLS are being re-wrote as http and not https - at least in my case that is the problem. If you view the page source and look for gtm.js its probably http://proxydomain and if your site is https the browser will block the elements because they're insecure.  At least this is what is happening on mine.
