### ISSUE TITLE
Optimize Javascript Loading

### ISSUE THREAD

**Issue by mlava** [optimalisatie/above-the-fold-optimization#60]
Hi again,
I am still having problems optimising my use of this plugin and would value some help.
If I turn on Optimize Javascript Loading I can no longer generate modal pop-ups using Convertplug.
If I turn it off the modals work as intended.

I tried adding the modal js files to the Ignore List and to the Async Disabled List.
Neither one helped me.

I don't know if I need to list the full path to the js files or just their file names.
The files are:
modal.min.js
functions-common.js
mailer.js
modal.common.js
modal.js
receiver.js

The path is:
wp-content/plugins/convertplug/modules/modal/assets/js

Please advise further :smile: 
Thanks!

**Comment by mlava** [comment]
@optimalisatie 
Any advice?
I have proxy working well but can't seem to get javascript optimisation...

**Comment by mlava** [comment]
Any hints @optimalisatie 
Or anyone else?
Sorry for being a noob, would really like to be using this plugin but having trouble with config.
Cheers 😄

**Comment by optimalisatie** [comment]
Hi @mlava,

Our apologies for the late reply. 

Some scripts do not natively support asynchronous loading. More information can be found in the following article about making Google AdSense scripts async compatible:

https://support.google.com/adsense/answer/3221666?hl=en

To solve the issue quickly it may be an option to exclude the conflicting scripts. For some scripts it may be a solution to encapsulate the code in `jQuery(function($) { ... });` This could be done with a WordPress filter or with the new HTML search and replace admin:

![image](https://user-images.githubusercontent.com/8843669/29856707-f588dca2-8d54-11e7-82cd-4c8b277a0c60.png)

```php
function pagespeed_filter_html($searchreplace)
{
    list($search, $replace, $search_regex, $replace_regex) = $searchreplace;

    # rewrite lsjQuery .ready() code
    $search_regex[] = '|(...script code match...)|s';
    $replace_regex[] = 'jQuery(function($) { $1 });';

    return array($search,$replace,$search_regex,$replace_regex);
}
add_filter('abtf_html_replace', 'pagespeed_filter_html', 10, 1);
```

If you use Autoptimize for minification of inline javascript you could use a filter by Autoptimize:

```php
function pagespeed_filter_inline_js($JS)
{
    if (strpos($JS, '(...script code to match...)') !== false) {
        $JS = preg_replace('|(...script code match...)|s', 'jQuery(function($) { $1 });', $JS);
    }
    return $JS;
}
add_filter('autoptimize_js_after_minify', 'pagespeed_filter_inline_js', 10, 2);
```

To understand the issue with async loading: some scripts depend on other scripts and when loading scripts asynchronously, the scripts will try to load as fast as possible independent from each other and independent from the HTML document. For some requests, the javascript files may be executed seconds after the HTML is loaded. For cached requests however, a script may be executed before the start of the HTML body. This may cause issues for some scripts. Using the jQuery encapsulation solution will make a script execute after the HTML is loaded, providing in stability that is sufficient for most scripts. When there are special dependencies however (such as with Google AdSense), it may be a little more complex to solve the issue.

Let me know if you manage to resolve the issue!

**Comment by mlava** [comment]
Hey, no problem. Thanks for the reply.
Can you give me any pointers on figuring out which script is the problem?
I've been using debug mode but can't seem to get the right script to ignore...
Thanks again 😄

**Comment by mlava** [comment]
I think I might have gotten somewhere by deleting my W3TC cache and retrying...

I think the error comes with js minification turned on w3TC...

Is there any way to run W3TC and ABTF together? Just turn off JS minification in W3TC?

Thanks

**Comment by gnanet** [comment]
In w3tc you have the option to disable js minification entirely, or  exclude scripts from minification, which helps to do a detection step by step. I also remember seeing some snippet that prints the scripts loaded into the first line of the page. I will try to find it quick from my notes, and paste you the link.

**Comment by gnanet** [comment]
Found this article, which contains the snippet too:
https://wpshout.com/make-site-faster-async-deferred-javascript-introducing-script_loader_tag/

**Comment by gnanet** [comment]
Reading a lot now about moving jquery to footer, and why that not happens always: if any script is loaded with wp-enqueue-script and jquery as its dependency, jquery will be loaded into head, which is the right thing and the cause enqueue system exsist. If anything stops working, it either does not use the enqueue system, or you managed to deactivate the dependency loading of jquery.

It is a huge job to design a website with abtf content that does not require any jquery in head, this is my conclusion after reaching 100/100 on both mobile and desktop PageSpeed Insights test, and saw that to accomplish this i had an almost non functioning site below the fold, and was missing menu on  mobile, or even a simple to-top did not worked anymore.

**Comment by optimalisatie** [comment]
Hi mlava,

The issues are most likely not related to a conflict with W3TC but with the fact that javascript is combined and loaded differently than as it has been added in the HTML / en-queued by WordPress. It would be best to discover the exact javascript cause so that a custom solution (or quick fix) can be found. The advise from @gnanet could be followed to discover the origin script(s).

Excluding scripts is often not the best solution unless it is for an individual page (e.g. a contact form) that doesn't receive much traffic so that a quick fix is economically the best solution. Most scripts can be made async compatible.

@gnanet 
One of the innovations of the ABTF plugin is a jQuery stub which enables async loading of jQuery (from the header) without breaking inline usage of jQuery ready / event handlers. The jQuery stub is loaded inline from the header and places jQuery actions in a queue and applies the actions in the correct order automatically as soon as jQuery is available.

It is correct that in most cases the above the fold display should load without the use of jQuery to save over 250kb of data-transfer (just for jQuery). Often there are CSS based alternatives for menu's, image sliders and other essential functionality that provide the exact same visual result and cost just a few kb of CSS that could be added to the critical CSS.

**Comment by gnanet** [comment]
Funny, i did a test on a clone of a live website, and started to fiddle with the Javascript settings, and hit exactly this issue [Pagespeed Insights test error for Mobile](https://wordpress.org/support/topic/unknown-error-in-google-pagespeed-insight-test/) and indeed my setting contains "HTML5 script loader"

I also tested with the little-loader only, but with that a lot of javascript code wont work, that worked with the "HTML5 script loader".

In my case the mobile detection of the theme fails completely with little-loader.

But is it somehow possible to use only the jQuery Stub to overcome the "render-blocking jquery.js"  ?

**Comment by optimalisatie** [comment]
Hi @gnanet,

The little-loader script loader by Walmart Labs should be very reliable. If it breaks anything, it's most likely the code or an async loading compatibility issue.

https://formidable.com/blog/2016/01/07/the-only-correct-script-loader-ever-made/

The HTML5 script loader uses a hard and stable fallback to little-loader so in essence it should be as stable as little-loader. If localStorage breaks for some reason, scripts will load using little-loader and there is almost no delay for the fallback so that there would be a limited performance hit compared to using little-loader, and a performance gain when it works correctly.

Our new plugin will contain a much more sophisticated and well developed script loader that goes a large step further then the ABTF script loader. It will make use of Fetch Stream API (with XHR for old browsers) to load scripts individually based on WordPress dependency configuration in a single optimized stream. It will add professional features like unused CSS stripping that have never been available to WordPress before.

We've had some funding issues but our engineers are working full time again so we do our best to have the new plugin completed a.s.a.p. It will be called Advanced WordPress Optimization.

**Comment by gnanet** [comment]
i have checked the "not working" parts and seems the jquery notation is wrong in the custom script.js of the theme, so step by step i hope to be able to fix the theme itself :D  

Also i think the whole story about "Optimize Javascript Loading" deserves a wiki page collecting all the info, so the initial issue can be processed, and maybe closed if its done
