### ISSUE TITLE
Disable Google fonts

### ISSUE THREAD

**Issue by Vidyut** [optimalisatie/above-the-fold-optimization#64]
Critical CSS contains google fonts - even when CSS is set to "disable google fonts"

**Comment by optimalisatie** [comment]
Hi Vidyut,

Thank you for your feedback!

Regarding the issue. Critical CSS is managed on the Critical CSS tab and the output is exactly as configured (unmodified). If there are Google fonts in the Critical CSS that you don't want to load then you should remove them manually. 

When you want to load the Google fonts locally it may be best to load the corresponding CSS in the critical CSS. We usually create an extra conditional critical CSS entry without conditions and with the option "_Prepend to any_" specifically for web fonts (including font awesome etc):

![webfonts](https://user-images.githubusercontent.com/8843669/29808032-cc97f5f8-8c96-11e7-81aa-2c069a3816b6.png)

The option _Prepend to any_ causes the font CSS to be included before other Critical CSS on a page so that rendering of the critical CSS that uses the fonts is smooth.

**Comment by Vidyut** [comment]
Ok. Maybe a note on the critical-css creator would help, in that case, so people know that they have to address that manually. I edited mine anyway, but thought it might be a bug, so reported.

**Comment by gnanet** [comment]
I have been playing with abtf yesterday evening, and i remember seeing somewhere exactly this note, that the user should use an _unconditional CriticalCSS_ with _Prepend to any_ maybe on the tab of local hosting the google fonts?

**Comment by HansVanEijsden** [comment]
Found it! 
![schermafbeelding 2017-08-29 om 17 03 22](https://user-images.githubusercontent.com/11890145/29828071-0bf10678-8cdc-11e7-93dd-1679f216990a.png)
