### ISSUE TITLE
Mobile menu problem

### ISSUE THREAD

**Issue by diossido** [optimalisatie/above-the-fold-optimization#78]
Hello.
I've added Above the Fold Optimization plugin to my site.

It seems to work very well (reach over 90 speedtest mobile and over 95 from desktop).

But I've found a big bug from my mobile device (android phone).

After plugin activation, the burger mobile menu doesen't work.

When i PUSH IT, it doesen't open and my site url, https://seo-wordpress.it/,  change in https://seo-wordpress.it/#

So users cannot navigate my site pages from mobile.
![screenshot_2017-11-03-16-43-32](https://user-images.githubusercontent.com/33353722/32382775-6dd11bea-c0b6-11e7-8f71-1dd816de759d.png)

**Comment by diossido** [comment]
Just an update.

It seems to be a problem with Javascripts optimization. If I disable the JS optimization the menu working fine.

**Comment by optimalisatie** [comment]
Hi diossido,

Thank you for your feedback!

Regrettably, the issue is related to javascript compatibility issues. I've answered similar questions in the past with suggestions how the issue can be resolved. It requires some tuning / advanced optimization of the javascript.

https://github.com/optimalisatie/above-the-fold-optimization/issues/70#issuecomment-330082200

Please let us know if you manage to resolve the issue!
