### ISSUE TITLE
AMP Page failure when CSS loaded from CDN - duplicate path on cache dir

### ISSUE THREAD

**Issue by supernovae** [optimalisatie/above-the-fold-optimization#86]
Google started alerting me that my AMP pages are failing after enabling CSS caching on CDN

Invalid value for attribute in CSS 'href' in tag 'link rel=stylesheet for fonts'

`<link
rel='stylesheet' id='font-awesome-css'  href='https://cdn.rockchucksummit.com/wp-content/cache/abtf/proxy/wp-content/cache/abtf/proxy/7d/99/03/7d99030837a4e31af45a406fbd7bce91.css' type='text/css' media='all' />`

Looks like the path is getting pushed twice?

wp-content/cache/abtf/proxy/ and wp-content/cache/abtf/proxy/ munged together there?

If I remove the duplicate path, it works fine in the URI and i'm assuming that will fix googles errors.

**Comment by supernovae** [comment]
ahh you know what, I may have defined the cdn proxy with that path.. checking it out :) lol

**Comment by optimalisatie** [comment]
Please let us know if you managed to resolve the issue!

Our upcoming Advanced Optimization plugin will contain a new innovation called `CDN mask`. It will enable to set the path for the CDN so that it will be possible to for example load assets in the directory `/wp-content/themes/theme-name/` from the root of a CDN host, e.g. `https://theme-cdn.rockchucksummit.com/style.css`. 

![image](https://user-images.githubusercontent.com/8843669/35376142-04b48fcc-01aa-11e8-94ef-fd0eb456b8b5.png)
