### ISSUE TITLE
Problem incompatibility with wordpress

### ISSUE THREAD

**Issue by antonioflo** [optimalisatie/above-the-fold-optimization#87]
After the last update there was an incompatibility problem with the wordpress theme panel. The codes do not work in the ads section.

**Comment by optimalisatie** [comment]
Hi antonioflo,

Thank you for reporting the issue!

Could you please provide us with more details? Is there an error visible in the browser console?

**Comment by antonioflo** [comment]
How can I carry out this type of check?

2018-01-25 22:26 GMT+01:00 Jan Jaap <notifications@github.com>:

**Comment by optimalisatie** [comment]
You can open the browser console with key `F12`.

https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by antonioflo** [comment]
Result of the console:

JQMIGRATE: Migrate is installed, version 1.4.1
(index):1 The SSL certificate used to load resources from
https://mr.comingsoon.it will be distrusted in M70. Once distrusted, users
will be prevented from loading these resources. See
https://g.co/chrome/symantecpkicerts for more information.
(index):22 GET
https://www.quotidianpost.it/?url=https%3A//servicer.mgid.com/161511/1%3Fw%3D675%26h%3D146%26cols%3D2%26pv%3D5%26cbuster%3D1516990406711976594090%26ref%3Dhttps%253A%252F%252Fwww.quotidianpost.it%252F%26pr%3Dwww.quotidianpost.it%26lu%3Dhttps%253A%252F%252Fwww.quotidianpost.it%252Fla-vedova-winchester-dalla-ghost-story-con-helen-mirren-poster-e-trailer-italiani-del-film%252F%26pageView%3D1%26pvid%3D16133aca038b0461d37&type=js&abtf-proxy=88668cffdb3c8ef5d04ceb6e0917a8f5
net::ERR_ABORTED
d.(anonymous function).appendChild @ (index):22
MarketGidBaseBlockC161511.ZF @ quotidianpost.it.161511.js?t=11802619:1
MarketGidBaseBlockC161511.start @ quotidianpost.it.161511.js?t=11802619:1
(anonymous) @ quotidianpost.it.161511.js?t=11802619:1
(index):1 The resource
https://adservice.google.com/adsid/integrator.js?domain=www.quotidianpost.it
was preloaded using link preload but not used within a few seconds from the
window's load event. Please make sure it wasn't preloaded for nothing.
(index):1 The resource
https://adservice.google.it/adsid/integrator.js?domain=www.quotidianpost.it
was preloaded using link preload but not used within a few seconds from the
window's load event. Please make sure it wasn't preloaded for nothing.

2018-01-26 14:09 GMT+01:00 Jan Jaap <notifications@github.com>:

**Comment by antonioflo** [comment]
Now it's also incompatible with google analytics and I've been forced to
disable your plugin. Let me know if you solve.

2018-01-26 19:08 GMT+01:00 Antonio Flora <antoniofidelity@gmail.com>:

**Comment by optimalisatie** [comment]
The issue appears to be related to the javascript proxy. To prevent proxy related issues you could disable the proxy or specifically configure what resources to proxy.

It may be that a plugin conflicts with the PHP proxy processor. This could occur when for example a plugin contains a bug or sends output before the proxy is started, causing the proxy to fail or contents to be malformed. It may also be that the proxy is bypassed completely due to the conflict and therefor any proxified URLs contain invalid contents / do not load.

A solution would be to define proxied resources in the preload list so that they will load from the static cache URL bypassing PHP logic (making it both faster and bypassing any other plugin).

The error shows `net::ERR_ABORTED`. It may be that a HTTP 500 Server Error is the cause which may indicate that there is a error message available in the server log. That message could provide a clue to the exact cause of the conflict (what plugin is involved / conflicting).
