### ISSUE TITLE
critical CSS no longer load instantly after plugin update to Version 2.9.8

### ISSUE THREAD

**Issue by yelnyaface** [optimalisatie/above-the-fold-optimization#88]
hi,
before the plugin is updated the minified critical CSS loads fast and almost instantly,

now if I press F5 or load the website for the first time I can see the CSS not loading properly for a short few seconds

for example: 

http://prntscr.com/i6e4l0
https://rasamalaysia.com/recipe-index-gallery/

did something changed in the plugin?

**Comment by optimalisatie** [comment]
Hi yelnyafac,

Thank you for reporting the issue!

In regards to your question, the loading of critical CSS didn't change in the last update. 

Did you try the critical CSS editor and quality test to see if the correct critical CSS source files are loaded for the specific page?

https://rasamalaysia.com/recipe-index-gallery/?critical-css-editor=1

It appears that just 1 critical CSS file is loaded which does not provide a quality above the fold display, causing a flash of unstyled content (FOUC).

https://en.wikipedia.org/wiki/Flash_of_unstyled_content

When I press F5 for cached requests, the FOUC is almost not visible. It may be that you didn't notice it before because of efficient browser caching of the full CSS.

**Comment by yelnyaface** [comment]
`It appears that just 1 critical CSS file is loaded which does not provide a quality above the fold display, causing a flash of unstyled content (FOUC).`

do you mean I should add in page specific critical CSS?

**Comment by optimalisatie** [comment]
Hi yelnyaface,

How did you create the Critical CSS? 

The quality of the critical CSS for the gallery page appears to be perfect now. I see you have added a conditional critical CSS file `@critical-css-file page-is-recipe-index-gallery.css`

The CSS is not compressed, it is advised to compress the critical CSS to reduce the size and improve performance (and Google's speed related scores).
