### ISSUE TITLE
HTTP/2 does not respect minified JS and CSS files

### ISSUE THREAD

**Issue by aamir2007** [optimalisatie/above-the-fold-optimization#95]
By the way its a great feature to have HTTP/2 server push on this plugin.
I have to use Autoptmize to minfy my JS and CSS files as your plugin does not seems to have this most important feature.
The issue is when I activate HTTP/2 it does not seem to respect Autoptimize minified js and css files instead it loads all the individual files along with Autoptimize minfied files resulting in around 30 to 40 warning messages in browser console stating "The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing."

Kindly look into this matter ASAP. Following is the url to my site.
https://gilli.tv/

Kind Regards,
Aamir

**Comment by optimalisatie** [comment]
Hi Aamir2007,

Thank you for your feedback!

We have published two new plugins:

- [HTTP/2 Optimization](https://github.com/o10n-x/wordpress-http2-optimization) ([documentation](https://github.com/o10n-x/wordpress-http2-optimization/tree/master/docs))
- [CSS Optimization](https://github.com/o10n-x/wordpress-css-optimization) (includes minification, concatenation, critical CSS)

We are currently developing new optimization plugins that will replace the Page Speed Optimization plugin.

Our original concept was much more advanced and used a JSON profile based configuration system that enables to configure 10.000+ optimization settings individually conditionally based on environment factors such as for example the `Save-Data` header or specifically change a few settings for "iPhone 5" devices but due to lack of funding we have chosen create a step in between with JSON like configuration, but just a single profile for a complete website, and to cut the plugin into individual [optimization modules](https://github.com/o10n-x) that can be used both standalone and together with a selection of modules with single plugin performance. An advantage of the new concept is that the focus for each plugin (and it's support requests / feedback) will lay at a single aspect of website performance optimization, making it more efficient to improve the plugins and gather knowledge about optimization.

WordPress has been blocking plugin submission for more than a week but the plugins can be downloaded from Github.

https://github.com/o10n-x/

Currently available:

– HTTP/2 Optimization
– Web Font Optimization
– CSS Optimization
– Security Header Optimization

Next weeks:
– HTML Optimization
– Javascript Optimization
– Progressive Web App Optimization
– Page Cache Optimization
– HTTP Cache Header Optimization

We have published a new CSS Optimization plugin that provides many new options and better optimization quality. 

https://github.com/o10n-x/wordpress-css-optimization

If you would be interested to install the new CSS Optimization plugin, you can simply download the zip file and unzip it in the plugin directory /wp-content/plugins/.

The new optimization plugins will replace the existing Page Speed Optimization plugin. The currently missing plugins are Javascript Optimization and Progressive Web App Optimization. Those plugins will be available soon.

The CSS editor of the CSS Optimization plugin is available with +30 themes that enables more efficient CSS editing while it also contains many professional tools such as CSS Lint and Clean CSS (professional).

![codemirror-css](https://user-images.githubusercontent.com/8843669/36474718-a39f7562-16f8-11e8-9b69-133accff02ba.png)

Critical CSS management is also more efficient in the new plugin so we advise to use the new plugin for CSS and Critical CSS optimization.

The new plugins will initially be documented on Github (beta documentation) and when the project acquires funding / finds someone interested to write documentation, it will be improved.

https://github.com/o10n-x/wordpress-http2-optimization/tree/master/docs

https://github.com/o10n-x/wordpress-font-optimization/tree/master/docs

**Comment by optimalisatie** [comment]
Javascript optimization is available for testing as well.

https://github.com/o10n-x/wordpress-javascript-optimization

![js-op1](https://user-images.githubusercontent.com/8843669/36498372-5f116f22-173e-11e8-9347-ccfb0eec6e38.png)

A new innovation is timed javascript execution. It will enable even the most javascript heavy websites to achieve the fastest first page load speed and performance scores. Scripts can be loaded in the background on domready or CPU idle time and executed on element scrolled into view, a Media Query and other methods.
