### ISSUE TITLE
CSS & Javascript optimisation options not really working

### ISSUE THREAD

**Issue by earcos** [optimalisatie/above-the-fold-optimization#97]
Hi,

Some of the CSS and Javascript optimisation options on the plugin are not really working. For example: adding a css on the CSS delivery optimisation remove list do not remove the file and adds it inline on the document.

Same thing happens to the Javascript optimisation part of the plugin

I tried to switch to the new CSS and Javascript optimisation plugins but they are not really working, with some options not working correctly.

I was wondering if the reason is that, as the documentation states, when I activated the new plugins, the old plugin disabled optimisation features, but they are not re-enabled when I uninstalled the new plugins.

Is there a way to find out if this is happening and re-activating optimisation features on the old plugin until the new ones are better?

As always, thanks a lot for all your help, I'll be glad to give you more information or help in any way necessary to improve your plugins.

**Comment by optimalisatie** [comment]
Hi earcos,

Thank you very much for your feedback!

The issue that you describe with the ABTF plugin should not be possible. It has never been reported before.

The following code is used to delete stylesheets that are on the delete-list. It is a simple search/replace.

```php
// match file against delete list
if (!empty($deletelist)) {
	$delete = false;
	foreach ($deletelist as $deleted_file_string) {
	    if (strpos($file, $deleted_file_string) !== false) {
		$delete = true;
		break 1;
	    }
	}
	if ($delete) {
	    $search[] = $matchedTag;
	    $replace[] = '';
	    continue;
	}
}
```

In regards to the new plugins disabling the ABTF plugin, it is based on plugin activation so when you would de-activate the new optimization plugin the ABTF plugin functionality should instantly be restored.

In regards to the new optimization plugins. We created a sort of quick bridge between the old ABTF plugin and our planned Advanced Optimization plugin and cut it in individual optimization modules. The new optimization plugins contain a lot of new options but it’s just about 20-30% of what the Advanced Optimization plugin would offer.

The javascript plugin contained some bugs that have been fixed in `v0.0.21`. The plugin wasn't automatically compatible with the ABTF plugin, the latest ABTF update `v2.9.15` automatically excludes the ABTF client from javascript optimization to make it better compatible.

We are using the new plugins on www.e-scooter.co and several other production websites.

If you would have the time to test the new plugins again we are very interested in your feedback! Any issues will be resolved a.s.a.p.

**Comment by earcos** [comment]
Than I must be doing something wrong. Is there a correct way to include names of css files to be deleted and included inline?

Thanks a lot!

**Comment by optimalisatie** [comment]
The check performed is a simple PHP `strpos` so any regular string that matches a stylesheet element should work.

It may be best to use the new plugin. You can delete a stylesheet using the URL filter:

```json
[
  {
    "url": "string-to-match",
    "delete": true
  },
  {
    "url": "/regex-string-to-match/i",
    "regex": true,
    "delete": true
  }
]
```

![image](https://user-images.githubusercontent.com/8843669/37251578-0b0a6c70-2513-11e8-885a-3d2bc82f7bef.png)
